-- CreateTable
CREATE TABLE "StrongPasswordKnowledgeTest" (
    "id" SERIAL NOT NULL,
    "name" TEXT NOT NULL,
    "qd1" TEXT NOT NULL,
    "qd2" TEXT NOT NULL,
    "qo1" TEXT NOT NULL,
    "qo2" TEXT NOT NULL,
    "qo3" TEXT NOT NULL,
    "qo4" TEXT NOT NULL,
    "qo5" TEXT NOT NULL,
    "qo6" TEXT NOT NULL,
    "qo7" TEXT NOT NULL,
    "qo8" TEXT NOT NULL,
    "qo9" TEXT NOT NULL,
    "qo10" TEXT NOT NULL,
    "qo11" TEXT NOT NULL,
    "qo12" TEXT NOT NULL,
    "qo13" TEXT NOT NULL,
    "qo14" TEXT NOT NULL,
    "qo15" TEXT NOT NULL,
    "qo16" TEXT NOT NULL,
    "qo17" TEXT NOT NULL,
    "qo18" TEXT NOT NULL,
    "qo19" TEXT NOT NULL,
    "qo20" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "StrongPasswordKnowledgeTest_pkey" PRIMARY KEY ("id")
);
