-- CreateTable
CREATE TABLE "UsabilitySurvey" (
    "id" SERIAL NOT NULL,
    "q1" INTEGER NOT NULL,
    "q2" INTEGER NOT NULL,
    "q3" INTEGER NOT NULL,
    "q4" INTEGER NOT NULL,
    "q5" INTEGER NOT NULL,
    "q6" INTEGER NOT NULL,
    "q7" INTEGER NOT NULL,
    "q8" INTEGER NOT NULL,
    "q9" INTEGER NOT NULL,
    "q10" INTEGER NOT NULL,
    "q11" INTEGER NOT NULL,
    "q12" INTEGER NOT NULL,
    "q13" INTEGER NOT NULL,
    "q14" INTEGER NOT NULL,
    "q15" INTEGER NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "UsabilitySurvey_pkey" PRIMARY KEY ("id")
);
