name: Cypress and Jest Tests

on: push

jobs:
  cypress-jest-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: yarn install
      - name: Run Jest tests
        run: yarn test
      - name: Run Cypress tests
        run: yarn cy:test
