name: Cypress and Jest Tests

on: push

jobs:
  cypress-jest-tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run Jest tests
        run: npm run test
      - name: Run Cypress tests
        run: npm run cy:test
